name: Build and Create Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Adjust to your required Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Compress .output into tarball
      run: |
        COMMIT_ID=$(git rev-parse --short HEAD)
        tar -czvf "./${COMMIT_ID}.tar.gz" -C .output .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Tag
    - uses: Klemensas/action-autotag@stable
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./${COMMIT_ID}.tar.gz  # Use the generated tarball for the release
        prerelease: false  # Optional: set this if the release is not a prerelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
