name: Build and Create Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Commit ID
      id: get_commit_id
      run: |
        COMMIT_ID=$(git rev-parse --short HEAD)
        echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Adjust to your required Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Compress .output into tarball
      run: |
        tar -czvf "./romsenmgr-$COMMIT_ID.tar.gz" -C .output .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create Git tag
      run: |
        COMMIT_ID=$(git rev-parse --short HEAD)
        git tag $COMMIT_ID
        git push origin $COMMIT_ID  # Ensure the tag is pushed to the remote repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          romsenmgr-${{ env.COMMIT_ID }}.tar.gz
        tag_name: ${{ env.COMMIT_ID }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
